'use strict';

/**
 * Minimal .env loader (no dependency) + configuration.
 * Values in the real environment always win over the .env file.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ENV_FILE = path.join(ROOT, '.env');

function loadEnvFile() {
  if (!fs.existsSync(ENV_FILE)) return;
  const raw = fs.readFileSync(ENV_FILE, 'utf8');
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = val;
  }
}

loadEnvFile();

const env = process.env;
const isProd = (env.NODE_ENV || 'development') === 'production';

function bool(v, dflt = false) {
  if (v === undefined || v === '') return dflt;
  return /^(1|true|yes|on)$/i.test(String(v));
}

const config = {
  root: ROOT,
  isProd,
  port: parseInt(env.PORT || '3000', 10),
  publicUrl: (env.PUBLIC_URL || `http://localhost:${env.PORT || 3000}`).replace(/\/$/, ''),
  // Behind nginx / a PaaS router this must be on, or secure cookies and
  // per-IP rate limiting both misbehave. Defaults to on in production.
  trustProxy: bool(env.TRUST_PROXY, isProd),

  dataDir: env.DATA_DIR || path.join(ROOT, 'data'),

  // 64 hex chars (32 bytes). Generated by `npm run init-secrets`.
  masterKeyHex: env.MASTER_KEY || '',
  sessionSecret: env.SESSION_SECRET || '',

  admin: {
    user: env.ADMIN_USER || 'admin',
    // Either a bcrypt hash (preferred) ...
    passwordHash: env.ADMIN_PASSWORD_HASH || '',
    // ... or a plaintext password which is hashed in memory at boot.
    password: env.ADMIN_PASSWORD || '',
  },

  smtp: {
    host: env.SMTP_HOST || '',
    port: parseInt(env.SMTP_PORT || '587', 10),
    secure: bool(env.SMTP_SECURE, false),
    user: env.SMTP_USER || '',
    pass: env.SMTP_PASS || '',
    from: env.MAIL_FROM || 'Microbiome 2026 <no-reply@example.org>',
    bcc: env.MAIL_BCC || '',
  },
};

config.smtp.enabled = Boolean(config.smtp.host);

module.exports = config;
